import { Octokit } from '@octokit/rest';
import type { Finding } from '../findings/schema.js';
import type { ReviewModeOutput } from '../modes/review.js';
import { log } from '../util/logger.js';

export interface PrPostOptions {
  owner: string;
  repo: string;
  prNumber: number;
  commitSha: string;
  token: string;
  /** Only post comments on files that are in the PR diff. */
  changedFiles: Set<string>;
}

/**
 * Posts the aggregated findings as a single GitHub PR review with
 * line-anchored comments. Comments are posted only for files that are
 * part of the PR diff (to avoid surfacing findings in unchanged files).
 */
export async function postPrReview(output: ReviewModeOutput, opts: PrPostOptions): Promise<void> {
  const octokit = new Octokit({ auth: opts.token });

  const inScope = output.findings.filter((f) => opts.changedFiles.has(f.file));
  const outOfScope = output.findings.length - inScope.length;

  const body = buildSummary(output, outOfScope);

  if (inScope.length === 0) {
    await octokit.pulls.createReview({
      owner: opts.owner,
      repo: opts.repo,
      pull_number: opts.prNumber,
      commit_id: opts.commitSha,
      event: 'COMMENT',
      body,
    });
    log.info('No findings on changed files — summary-only review posted.');
    return;
  }

  const comments = inScope.map((f) => ({
    path: f.file,
    line: Math.max(1, f.lineStart),
    side: 'RIGHT' as const,
    body: renderComment(f),
  }));

  await octokit.pulls.createReview({
    owner: opts.owner,
    repo: opts.repo,
    pull_number: opts.prNumber,
    commit_id: opts.commitSha,
    event: 'COMMENT',
    body,
    comments,
  });
  log.success(`Posted ${inScope.length} comments to ${opts.owner}/${opts.repo}#${opts.prNumber}`);
}

function buildSummary(output: ReviewModeOutput, outOfScope: number): string {
  const b = output.breakdown;
  const reviewerList = output.perReviewer
    .map((r) => `- **${r.reviewer}**: ${r.findings.length} findings${r.error ? ` (⚠️ ${r.error})` : ''}`)
    .join('\n');
  const sastList = `- **semgrep**: ${output.sast.semgrep.ran ? output.sast.semgrep.count : 'skipped'}
- **eslint**: ${output.sast.eslint.ran ? output.sast.eslint.count : 'skipped'}
- **npm-audit**: ${output.sast.npmAudit.ran ? output.sast.npmAudit.count : 'skipped'}`;

  return `## 🔒 Secure Review — multi-model security audit

**Findings:** ${output.findings.length}  ·  **Cost:** $${output.totalCostUSD.toFixed(3)}  ·  **Duration:** ${(output.totalDurationMs / 1000).toFixed(1)}s

| CRITICAL | HIGH | MEDIUM | LOW | INFO |
|---:|---:|---:|---:|---:|
| ${b.CRITICAL} | ${b.HIGH} | ${b.MEDIUM} | ${b.LOW} | ${b.INFO} |

### Reviewers
${reviewerList}

### SAST
${sastList}

${outOfScope > 0 ? `\n> ${outOfScope} finding(s) were in files not modified by this PR and are omitted.\n` : ''}
<sub>Generated by [secure-review](https://github.com/fonCki/secure-review) · multi-model security review for AI-generated code</sub>`;
}

function renderComment(f: Finding): string {
  const tags = [f.cwe, f.owaspCategory].filter(Boolean).join(' · ');
  const reporters = f.reportedBy.join(', ');
  const confidence = (f.confidence * 100).toFixed(0);
  const confidenceBadge =
    f.reportedBy.length >= 2 ? `🎯 ${confidence}% (${f.reportedBy.length} reviewers agree)` : `${confidence}%`;
  return `**${f.severity}** · ${f.title} ${tags ? `_(${tags})_` : ''}

${f.description}

${f.remediation ? `**Fix:** ${f.remediation}\n\n` : ''}---
<sub>reported by: ${reporters} · confidence: ${confidenceBadge}</sub>`;
}
