import type { Finding, SeverityBreakdown } from '../findings/schema.js';
import type { ReviewModeOutput } from '../modes/review.js';
import type { FixModeOutput, IterationRecord } from '../modes/fix.js';

/**
 * Self-contained interactive HTML report.
 *
 * Design goals:
 *   - Single file: inline CSS + vanilla JS, no CDN, no external fonts.
 *     The output renders the same on a developer's laptop, in CI artifacts,
 *     and in a thesis-presentation context (offline).
 *   - Mode-aware: review mode shows reviewer health + findings; fix mode
 *     adds a before/after delta, per-iteration timeline, and the resolved
 *     vs. introduced split per iteration.
 *   - Filter + sort client-side: agreement, severity, free-text search, and
 *     the option to peek at baseline-suppressed findings without re-running.
 *   - XSS-safe: every untrusted string is HTML-escaped; the embedded JSON
 *     payload is escaped with `\u003C` so a `</script>` in a title can't
 *     break out of the data block.
 */

interface ReportShell {
  title: string;
  subtitle: string;
  data: unknown;
  body: string;
}

export function renderReviewHtml(output: ReviewModeOutput): string {
  const data = {
    mode: 'review' as const,
    findings: output.findings,
    baselineSuppressed: output.baselineSuppressed ?? [],
    perReviewer: output.perReviewer.map((r) => ({
      reviewer: r.reviewer,
      findings: r.findings.length,
      costUSD: r.usage.costUSD,
      durationMs: r.durationMs,
      status: r.status,
      error: r.error,
    })),
  };

  const body = [
    summaryCards({
      breakdown: output.breakdown,
      totalCostUSD: output.totalCostUSD,
      totalDurationMs: output.totalDurationMs,
      totalFindings: output.findings.length,
      baselineSuppressed: data.baselineSuppressed.length,
      reviewStatus: output.reviewStatus,
      failedReviewers: output.failedReviewers,
    }),
    reviewerHealthSection(data.perReviewer),
    sastSection(output.sast),
    findingsSection(output.findings),
  ].join('\n');

  return shell({
    title: 'Secure Review Report',
    subtitle: `Generated ${new Date().toISOString()}`,
    data,
    body,
  });
}

export function renderFixHtml(output: FixModeOutput): string {
  const data = {
    mode: 'fix' as const,
    findings: output.finalFindings,
    baselineSuppressed: output.baselineSuppressed ?? [],
    iterations: output.iterations.map((it) => ({
      iteration: it.iteration,
      reviewer: it.reviewer,
      findingsBefore: it.findingsBefore.length,
      findingsAfter: it.findingsAfter.length,
      resolved: it.resolvedFindings,
      introduced: it.introducedFindings,
      newCritical: it.newCritical,
      costUSD: it.costUSD,
    })),
  };

  const body = [
    summaryCards({
      breakdown: output.finalBreakdown,
      totalCostUSD: output.totalCostUSD,
      totalDurationMs: output.totalDurationMs,
      totalFindings: output.finalFindings.length,
      baselineSuppressed: data.baselineSuppressed.length,
      reviewStatus: output.reviewStatus,
      failedReviewers: output.failedReviewers,
      gateBlocked: output.gateBlocked,
      gateReasons: output.gateReasons,
    }),
    beforeAfterSection(output.initialBreakdown, output.finalBreakdown, output.initialFindings.length, output.finalFindings.length),
    iterationsSection(output.iterations),
    filesChangedSection(output.filesChanged),
    findingsSection(output.finalFindings, 'Remaining findings'),
  ].join('\n');

  return shell({
    title: 'Secure Review — Fix Mode',
    subtitle: `Generated ${new Date().toISOString()}`,
    data,
    body,
  });
}

// ---------------------------------------------------------------------------
// Shell (head + header + frame + scripts)
// ---------------------------------------------------------------------------

function shell({ title, subtitle, data, body }: ReportShell): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="generator" content="secure-review" />
<title>${escapeHtml(title)}</title>
<style>${CSS}</style>
</head>
<body>
<header class="topbar">
  <div class="brand">
    <span class="logo" aria-hidden="true">◆</span>
    <span class="brand-text">${escapeHtml(title)}</span>
  </div>
  <div class="brand-sub">${escapeHtml(subtitle)}</div>
</header>
<main>
${body}
</main>
<footer class="foot">Generated by <code>secure-review</code> · open this file in any browser; no network calls are made.</footer>
<script id="sr-data" type="application/json">${escapeJsonForScript(data)}</script>
<script>${JS}</script>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

interface SummaryCardsInput {
  breakdown: SeverityBreakdown;
  totalCostUSD: number;
  totalDurationMs: number;
  totalFindings: number;
  baselineSuppressed: number;
  reviewStatus: 'ok' | 'degraded' | 'failed';
  failedReviewers: string[];
  gateBlocked?: boolean;
  gateReasons?: string[];
}

function summaryCards(s: SummaryCardsInput): string {
  const statusLabel =
    s.reviewStatus === 'ok'
      ? `<span class="status ok">OK</span>`
      : s.reviewStatus === 'degraded'
        ? `<span class="status degraded">DEGRADED</span><span class="status-detail">${escapeHtml(s.failedReviewers.join(', '))}</span>`
        : `<span class="status failed">FAILED</span>`;
  const gate =
    s.gateBlocked === undefined
      ? ''
      : s.gateBlocked
        ? `<div class="card stat warn">
            <div class="stat-label">Gate</div>
            <div class="stat-value">BLOCKED</div>
            <div class="stat-foot">${escapeHtml((s.gateReasons ?? []).join(' · ') || '—')}</div>
          </div>`
        : `<div class="card stat ok">
            <div class="stat-label">Gate</div>
            <div class="stat-value">PASSED</div>
          </div>`;
  return `<section class="grid">
  <div class="card stat">
    <div class="stat-label">Findings</div>
    <div class="stat-value">${s.totalFindings}</div>
    ${s.baselineSuppressed > 0 ? `<div class="stat-foot muted">+${s.baselineSuppressed} baselined</div>` : ''}
  </div>
  <div class="card stat">
    <div class="stat-label">Cost</div>
    <div class="stat-value">$${s.totalCostUSD.toFixed(3)}</div>
    <div class="stat-foot muted">${(s.totalDurationMs / 1000).toFixed(1)}s</div>
  </div>
  <div class="card stat">
    <div class="stat-label">Status</div>
    <div class="stat-value">${statusLabel}</div>
  </div>
  ${gate}
  <div class="card breakdown">
    <div class="stat-label">Severity</div>
    <div class="bars">
      ${severityBar('CRITICAL', s.breakdown.CRITICAL)}
      ${severityBar('HIGH', s.breakdown.HIGH)}
      ${severityBar('MEDIUM', s.breakdown.MEDIUM)}
      ${severityBar('LOW', s.breakdown.LOW)}
      ${severityBar('INFO', s.breakdown.INFO)}
    </div>
  </div>
</section>`;
}

function severityBar(severity: string, count: number): string {
  return `<div class="bar bar-${severity.toLowerCase()}">
    <span class="bar-label">${severity}</span>
    <span class="bar-count">${count}</span>
  </div>`;
}

function reviewerHealthSection(
  perReviewer: { reviewer: string; findings: number; costUSD: number; durationMs: number; status: string; error?: string }[],
): string {
  if (perReviewer.length === 0) return '';
  const rows = perReviewer
    .map(
      (r) => `<tr>
        <td>${escapeHtml(r.reviewer)}</td>
        <td class="num">${r.findings}</td>
        <td class="num">$${r.costUSD.toFixed(3)}</td>
        <td class="num">${(r.durationMs / 1000).toFixed(1)}s</td>
        <td>${r.error ? `<span class="status failed">FAILED</span><span class="status-detail">${escapeHtml(r.error)}</span>` : `<span class="status ok">${escapeHtml(r.status)}</span>`}</td>
      </tr>`,
    )
    .join('\n');
  return `<section class="card pad">
    <h2>Per-reviewer health</h2>
    <table><thead><tr>
      <th>Reviewer</th><th>Findings</th><th>Cost</th><th>Duration</th><th>Status</th>
    </tr></thead><tbody>${rows}</tbody></table>
  </section>`;
}

function sastSection(sast: ReviewModeOutput['sast']): string {
  const row = (name: string, r: { ran: boolean; count: number; error?: string }) =>
    `<tr>
      <td>${escapeHtml(name)}</td>
      <td>${r.ran ? '✓' : '⚠︎'}</td>
      <td class="num">${r.count}</td>
      <td class="muted">${escapeHtml(r.error ?? '')}</td>
    </tr>`;
  return `<section class="card pad">
    <h2>SAST</h2>
    <table><thead><tr><th>Tool</th><th>Ran?</th><th>Findings</th><th>Note</th></tr></thead>
    <tbody>
      ${row('semgrep', sast.semgrep)}
      ${row('eslint', sast.eslint)}
      ${row('npm-audit', sast.npmAudit)}
    </tbody></table>
  </section>`;
}

function beforeAfterSection(
  initial: SeverityBreakdown,
  final: SeverityBreakdown,
  initialTotal: number,
  finalTotal: number,
): string {
  const sevs: (keyof SeverityBreakdown)[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
  const rows = sevs
    .map((k) => {
      const d = final[k] - initial[k];
      const cls = d < 0 ? 'good' : d > 0 ? 'bad' : 'flat';
      const sign = d > 0 ? '+' : '';
      return `<tr>
        <td><span class="sev-pill bar-${k.toLowerCase()}">${k}</span></td>
        <td class="num">${initial[k]}</td>
        <td class="num">${final[k]}</td>
        <td class="num delta ${cls}">${sign}${d}</td>
      </tr>`;
    })
    .join('\n');
  const totalDelta = finalTotal - initialTotal;
  const totalCls = totalDelta < 0 ? 'good' : totalDelta > 0 ? 'bad' : 'flat';
  return `<section class="card pad">
    <h2>Before vs after</h2>
    <table>
      <thead><tr><th>Severity</th><th>Initial</th><th>Final</th><th>Δ</th></tr></thead>
      <tbody>${rows}</tbody>
      <tfoot><tr>
        <td><strong>Total</strong></td>
        <td class="num"><strong>${initialTotal}</strong></td>
        <td class="num"><strong>${finalTotal}</strong></td>
        <td class="num delta ${totalCls}"><strong>${totalDelta > 0 ? '+' : ''}${totalDelta}</strong></td>
      </tr></tfoot>
    </table>
  </section>`;
}

function iterationsSection(iterations: IterationRecord[]): string {
  if (iterations.length === 0) return '';
  const rows = iterations
    .map(
      (it) => `<tr>
        <td class="num">${it.iteration}</td>
        <td>${escapeHtml(it.reviewer)}</td>
        <td class="num">${it.findingsBefore.length}</td>
        <td class="num">${it.findingsAfter.length}</td>
        <td class="num good">${it.resolved}</td>
        <td class="num ${it.introducedFindings.length > 0 ? 'bad' : 'flat'}">${it.introducedFindings.length}${it.newCritical > 0 ? ` <span class="crit-tag">(${it.newCritical} CRITICAL)</span>` : ''}</td>
        <td class="num">$${it.costUSD.toFixed(3)}</td>
      </tr>`,
    )
    .join('\n');

  const detail = iterations
    .map((it) => {
      if (it.resolvedFindings.length === 0 && it.introducedFindings.length === 0) return '';
      return `<details class="card iter-detail">
          <summary>Iteration ${it.iteration} — ${escapeHtml(it.reviewer)}: <span class="good">${it.resolvedFindings.length} resolved</span> · <span class="bad">${it.introducedFindings.length} introduced</span></summary>
          ${deltaList('Resolved', it.resolvedFindings, 'good')}
          ${deltaList('Introduced', it.introducedFindings, 'bad')}
        </details>`;
    })
    .join('\n');

  return `<section class="card pad">
    <h2>Iterations</h2>
    <table>
      <thead><tr><th>#</th><th>Verifier</th><th>In</th><th>Out</th><th>Resolved</th><th>Introduced</th><th>Cost</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <p class="muted small">
      <em>In</em> = what the writer addressed this iteration (initial union for iter 1, prior verifier audit for iter 2+). <em>Out</em> = what the rotating verifier saw afterwards. Same bug → same <code>S-NNN</code> across iterations (see <code>findings/identity.ts</code>).
    </p>
    ${detail ? `<div class="iter-details">${detail}</div>` : ''}
  </section>`;
}

function deltaList(label: string, findings: Finding[], cls: string): string {
  if (findings.length === 0) return '';
  const items = findings
    .map((f) => {
      const id = f.stableId ? `<code class="stable-id">${escapeHtml(f.stableId)}</code> ` : '';
      const cwe = f.cwe ? `<span class="tag">${escapeHtml(f.cwe)}</span>` : '';
      return `<li>${id}<span class="sev-pill bar-${f.severity.toLowerCase()}">${escapeHtml(f.severity)}</span> <code>${escapeHtml(f.file)}:${f.lineStart}</code> — ${escapeHtml(f.title)} ${cwe}</li>`;
    })
    .join('\n');
  return `<div class="delta-block ${cls}"><h4>${label} (${findings.length})</h4><ul>${items}</ul></div>`;
}

function filesChangedSection(files: string[]): string {
  if (files.length === 0) return '';
  return `<section class="card pad">
    <h2>Files changed (${files.length})</h2>
    <ul class="filelist">${files.map((f) => `<li><code>${escapeHtml(f)}</code></li>`).join('')}</ul>
  </section>`;
}

function findingsSection(findings: Finding[], heading = 'Findings'): string {
  return `<section class="card pad findings-section">
    <div class="findings-head">
      <h2>${escapeHtml(heading)} <span id="sr-count" class="muted small"></span></h2>
      <div class="filters">
        <input type="search" id="sr-search" placeholder="Search title, file, CWE, reporter…" autocomplete="off" />
        <select id="sr-sev" title="Minimum severity">
          <option value="INFO">All severities</option>
          <option value="LOW">≥ LOW</option>
          <option value="MEDIUM">≥ MEDIUM</option>
          <option value="HIGH">≥ HIGH</option>
          <option value="CRITICAL">CRITICAL only</option>
        </select>
        <select id="sr-agree" title="Minimum agreement">
          <option value="1">Any agreement</option>
          <option value="2">≥ 2 reporters</option>
          <option value="3">3 reporters</option>
        </select>
        <select id="sr-sort" title="Sort by">
          <option value="agreement">Sort: agreement</option>
          <option value="severity">Sort: severity</option>
          <option value="file">Sort: file</option>
        </select>
        <button data-toggle="all" data-action="expand" type="button" class="ghost">Expand all</button>
        <button data-toggle="all" data-action="collapse" type="button" class="ghost">Collapse all</button>
      </div>
    </div>
    <div id="sr-findings">${findings.length === 0 ? '<p class="muted">No findings.</p>' : ''}</div>
  </section>`;
}

// ---------------------------------------------------------------------------
// Inline assets
// ---------------------------------------------------------------------------

const CSS = `
:root {
  color-scheme: light dark;
  --bg: #f6f7f9;
  --fg: #15171b;
  --muted: #6b7280;
  --card: #ffffff;
  --border: #e5e7eb;
  --accent: #2563eb;
  --good: #047857;
  --bad: #b91c1c;
  --flat: #6b7280;
  --shadow: 0 1px 2px rgb(0 0 0 / 6%), 0 4px 12px rgb(0 0 0 / 4%);
  --crit: #b91c1c;
  --high: #c2410c;
  --med:  #b45309;
  --low:  #2563eb;
  --info: #6b7280;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0d1117;
    --fg: #e6edf3;
    --muted: #8b95a3;
    --card: #161b22;
    --border: #30363d;
    --accent: #58a6ff;
    --good: #3fb950;
    --bad: #f85149;
    --flat: #8b95a3;
    --crit: #f85149;
    --high: #ff8d4a;
    --med:  #d29922;
    --low:  #58a6ff;
    --info: #8b95a3;
    --shadow: 0 1px 2px rgb(0 0 0 / 30%), 0 4px 12px rgb(0 0 0 / 25%);
  }
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--fg);
  font: 14px/1.55 ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  padding-bottom: 4rem;
}
code { font-family: ui-monospace, SFMono-Regular, "JetBrains Mono", Menlo, Consolas, monospace; font-size: 0.92em; background: rgb(127 127 127 / 8%); padding: 0.1em 0.35em; border-radius: 4px; }
.topbar {
  position: sticky; top: 0; z-index: 5;
  background: var(--card); border-bottom: 1px solid var(--border); box-shadow: var(--shadow);
  padding: 0.85rem 1.5rem; display: flex; align-items: baseline; justify-content: space-between;
}
.brand { display: flex; align-items: baseline; gap: 0.6rem; font-weight: 600; font-size: 1.05rem; }
.brand .logo { color: var(--accent); font-size: 1.3rem; }
.brand-sub { color: var(--muted); font-size: 0.85rem; font-variant-numeric: tabular-nums; }
main { max-width: 1100px; margin: 1.5rem auto; padding: 0 1.5rem; display: flex; flex-direction: column; gap: 1.25rem; }
section.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 0.75rem; }
.card { background: var(--card); border: 1px solid var(--border); border-radius: 10px; box-shadow: var(--shadow); }
.card.pad { padding: 1.1rem 1.25rem; }
.card.stat { padding: 0.9rem 1rem 0.85rem; }
.stat-label { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
.stat-value { font-size: 1.45rem; font-weight: 600; margin-top: 0.15rem; font-variant-numeric: tabular-nums; }
.stat-foot { font-size: 0.78rem; margin-top: 0.2rem; color: var(--muted); }
.muted { color: var(--muted); }
.small { font-size: 0.82rem; font-weight: 400; }
.card.warn .stat-value { color: var(--bad); }
.card.ok .stat-value { color: var(--good); }
.breakdown .bars { display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.35rem; margin-top: 0.5rem; }
.bar { background: rgb(127 127 127 / 6%); border: 1px solid var(--border); border-radius: 6px; padding: 0.35rem 0.45rem; text-align: center; }
.bar-label { display: block; font-size: 0.7rem; letter-spacing: 0.04em; color: var(--muted); text-transform: uppercase; }
.bar-count { display: block; font-size: 1.1rem; font-weight: 600; font-variant-numeric: tabular-nums; }
.bar-critical .bar-count, .bar-critical .bar-label { color: var(--crit); }
.bar-high .bar-count, .bar-high .bar-label { color: var(--high); }
.bar-medium .bar-count, .bar-medium .bar-label { color: var(--med); }
.bar-low .bar-count, .bar-low .bar-label { color: var(--low); }
.bar-info .bar-count, .bar-info .bar-label { color: var(--info); }
h2 { font-size: 1.05rem; margin: 0 0 0.7rem; letter-spacing: -0.01em; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 0.45rem 0.55rem; text-align: left; border-bottom: 1px solid var(--border); }
th { font-weight: 600; font-size: 0.82rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.03em; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.delta.good { color: var(--good); }
.delta.bad  { color: var(--bad); }
.delta.flat { color: var(--flat); }
.crit-tag { color: var(--crit); font-weight: 600; }
.status { display: inline-block; padding: 0.05rem 0.45rem; border-radius: 4px; font-size: 0.78rem; font-weight: 600; letter-spacing: 0.03em; }
.status.ok { color: var(--good); background: color-mix(in srgb, var(--good) 14%, transparent); }
.status.degraded { color: var(--med); background: color-mix(in srgb, var(--med) 14%, transparent); }
.status.failed { color: var(--bad); background: color-mix(in srgb, var(--bad) 14%, transparent); }
.status-detail { color: var(--muted); margin-left: 0.4rem; font-size: 0.8rem; }
.findings-head { display: flex; flex-wrap: wrap; gap: 0.7rem; align-items: center; justify-content: space-between; margin-bottom: 0.6rem; }
.filters { display: flex; flex-wrap: wrap; gap: 0.4rem; }
.filters input, .filters select, .filters button { font: inherit; padding: 0.3rem 0.55rem; border: 1px solid var(--border); border-radius: 6px; background: var(--card); color: var(--fg); }
.filters input { min-width: 220px; }
.filters button.ghost { cursor: pointer; }
.filters button.ghost:hover { background: rgb(127 127 127 / 8%); }
#sr-findings { display: flex; flex-direction: column; gap: 0.45rem; }
details.finding { background: var(--card); border: 1px solid var(--border); border-radius: 8px; transition: box-shadow 0.15s; }
details.finding[open] { box-shadow: var(--shadow); }
details.finding > summary {
  list-style: none;
  cursor: pointer;
  padding: 0.55rem 0.85rem;
  display: grid;
  grid-template-columns: auto auto 1fr auto auto;
  gap: 0.55rem;
  align-items: center;
}
details.finding > summary::-webkit-details-marker { display: none; }
.sev-pill { display: inline-block; padding: 0.05rem 0.45rem; border-radius: 4px; font-size: 0.72rem; font-weight: 700; letter-spacing: 0.04em; color: white; }
.sev-pill.bar-critical { background: var(--crit); }
.sev-pill.bar-high     { background: var(--high); }
.sev-pill.bar-medium   { background: var(--med); }
.sev-pill.bar-low      { background: var(--low); }
.sev-pill.bar-info     { background: var(--info); }
.stable-id { font-size: 0.75rem; color: var(--muted); }
.title { font-weight: 600; }
.meta { color: var(--muted); font-size: 0.85rem; }
.agree-badge { font-size: 0.78rem; padding: 0.05rem 0.45rem; border-radius: 4px; background: color-mix(in srgb, var(--accent) 14%, transparent); color: var(--accent); white-space: nowrap; }
.agree-badge.solo { background: rgb(127 127 127 / 10%); color: var(--muted); }
.body { padding: 0.4rem 0.85rem 0.85rem; border-top: 1px solid var(--border); }
.body p { margin: 0.45rem 0; }
.body .reporters { color: var(--muted); font-size: 0.85rem; }
.tag { display: inline-block; padding: 0.05rem 0.4rem; margin-right: 0.25rem; font-size: 0.75rem; border: 1px solid var(--border); border-radius: 4px; background: rgb(127 127 127 / 5%); color: var(--muted); }
.delta-block { padding: 0.4rem 0; }
.delta-block h4 { margin: 0.4rem 0 0.25rem; font-size: 0.9rem; }
.delta-block.good h4 { color: var(--good); }
.delta-block.bad  h4 { color: var(--bad); }
.delta-block ul { margin: 0; padding-left: 1.2rem; }
.delta-block li { margin: 0.2rem 0; }
.iter-detail { padding: 0.5rem 0.85rem; border: 1px solid var(--border); border-radius: 8px; background: var(--card); margin-top: 0.4rem; }
.iter-details { display: flex; flex-direction: column; gap: 0.4rem; margin-top: 0.6rem; }
.iter-detail summary { cursor: pointer; font-size: 0.92rem; }
.filelist { columns: 2; -webkit-columns: 2; margin: 0; padding-left: 1.1rem; }
.filelist li { break-inside: avoid; }
.foot { text-align: center; color: var(--muted); font-size: 0.82rem; margin-top: 1.5rem; }
@media (max-width: 720px) {
  details.finding > summary { grid-template-columns: auto 1fr auto; }
  .meta, .stable-id { display: none; }
  .filters input { min-width: 0; flex: 1; }
}
`;

const JS = `
(function () {
  var el = document.getElementById('sr-data');
  if (!el) return;
  var data;
  try { data = JSON.parse(el.textContent || '{}'); } catch (e) { return; }
  var findings = Array.isArray(data.findings) ? data.findings : [];
  var SEV = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1, INFO: 0 };

  var $list = document.getElementById('sr-findings');
  var $count = document.getElementById('sr-count');
  var $search = document.getElementById('sr-search');
  var $sev = document.getElementById('sr-sev');
  var $agree = document.getElementById('sr-agree');
  var $sort = document.getElementById('sr-sort');
  if (!$list) return;

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function card(f) {
    var sev = (f.severity || 'INFO').toLowerCase();
    var reporters = (f.reportedBy || []).join(', ');
    var agreement = (f.reportedBy || []).length;
    var conf = Math.round((f.confidence || 0) * 100);
    var tags = [f.cwe, f.owaspCategory].filter(Boolean)
      .map(function (t) { return '<span class="tag">' + esc(t) + '</span>'; })
      .join('');
    var stableTag = f.stableId
      ? '<code class="stable-id">' + esc(f.stableId) + '</code>'
      : '<span></span>';
    var agreeBadge = agreement > 1
      ? '<span class="agree-badge">✓ ' + agreement + ' models</span>'
      : '<span class="agree-badge solo">' + agreement + ' model</span>';
    return ''
      + '<details class="finding sev-' + sev + '"><summary>'
      +   '<span class="sev-pill bar-' + sev + '">' + esc(f.severity) + '</span>'
      +   stableTag
      +   '<span class="title">' + esc(f.title) + '</span>'
      +   '<span class="meta"><code>' + esc(f.file) + ':' + (f.lineStart | 0) + '</code></span>'
      +   agreeBadge
      + '</summary>'
      + '<div class="body">'
      +   '<p class="reporters">Reported by ' + esc(reporters || '—')
      +   ' · confidence ' + conf + '%'
      +   (f.id ? ' · <code>' + esc(f.id) + '</code>' : '')
      + '</p>'
      +   (tags ? '<p>' + tags + '</p>' : '')
      +   '<p class="desc">' + esc(f.description || '') + '</p>'
      +   (f.remediation ? '<p class="remediation"><strong>Remediation:</strong> ' + esc(f.remediation) + '</p>' : '')
      + '</div></details>';
  }

  function compare(a, b) {
    var s = $sort ? $sort.value : 'agreement';
    if (s === 'severity') return SEV[b.severity] - SEV[a.severity];
    if (s === 'file') {
      var c = (a.file || '').localeCompare(b.file || '');
      if (c !== 0) return c;
      return (a.lineStart | 0) - (b.lineStart | 0);
    }
    var byAgree = (b.reportedBy || []).length - (a.reportedBy || []).length;
    if (byAgree !== 0) return byAgree;
    return SEV[b.severity] - SEV[a.severity];
  }

  function render() {
    var q = ($search && $search.value || '').trim().toLowerCase();
    var minSev = $sev ? SEV[$sev.value] : 0;
    var minAgree = $agree ? parseInt($agree.value, 10) : 1;
    var visible = findings.filter(function (f) {
      if (SEV[f.severity] < minSev) return false;
      if ((f.reportedBy || []).length < minAgree) return false;
      if (q) {
        var hay = [f.title, f.description, f.file, f.cwe, f.owaspCategory, (f.reportedBy || []).join(' ')].join(' ').toLowerCase();
        if (hay.indexOf(q) === -1) return false;
      }
      return true;
    });
    visible.sort(compare);
    if (visible.length === 0) {
      $list.innerHTML = '<p class="muted">No findings match the current filters.</p>';
    } else {
      $list.innerHTML = visible.map(card).join('');
    }
    if ($count) $count.textContent = visible.length + ' / ' + findings.length;
  }

  ['input', 'change'].forEach(function (ev) {
    if ($search) $search.addEventListener(ev, render);
    if ($sev)    $sev.addEventListener(ev, render);
    if ($agree)  $agree.addEventListener(ev, render);
    if ($sort)   $sort.addEventListener(ev, render);
  });

  document.querySelectorAll('[data-toggle="all"]').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var open = btn.getAttribute('data-action') === 'expand';
      document.querySelectorAll('details.finding').forEach(function (d) { d.open = open; });
    });
  });

  render();
})();
`;

// ---------------------------------------------------------------------------
// Escape helpers
// ---------------------------------------------------------------------------

function escapeHtml(s: unknown): string {
  return String(s ?? '').replace(/[&<>"']/g, (c) => {
    switch (c) {
      case '&':
        return '&amp;';
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      case '"':
        return '&quot;';
      default:
        return '&#39;';
    }
  });
}

/**
 * Stringify `data` for safe embedding inside `<script type="application/json">`.
 * Replaces `<` with `\u003C` so a `</script>` substring inside a finding title
 * cannot terminate the data block (the spec requires a literal `</script` in
 * raw text — escaping `<` covers it without escaping `/`).
 *
 * Also escapes U+2028 and U+2029 so the embedded JSON parses identically when
 * the surrounding `<script>` happens to be served as JS (e.g. a future move
 * to `type="module"` or a tooling regression that strips the JSON type).
 */
function escapeJsonForScript(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, '\\u003C')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}
